// + Internationalisierung +

// window.currentLocaleKey = 'de'; // by now also: en , fr , es 
window.currentLocaleKey = 'en'; 
window.currency="€";

const locales = {
	"de": {
		// --- Navigation / Global ---
		"app_title": "Haushaltsbuch",
		"nav_home": "Start",
		"nav_import": "Import",
		"nav_categorize": "Kategorisierung",
		"nav_visualize": "Visualisierung",
		"btn_reset": "Reset",
		"btn_save_json": "JSON Speichern",
		"btn_export_csv": "CSV Exportieren",
		"status_placeholder": "Status Nachrichten hier.",
		"modal_title_confirm": "Bestätigung erforderlich",
		"modal_message_default": "Sind Sie sicher, dass Sie diese Aktion durchführen möchten?",
		"modal_btn_cancel": "Abbrechen",
		"modal_btn_confirm": "Bestätigen",
		
		// --- Home Page ---
		"home_welcome_title": "Willkommen!",
		"home_welcome_text": "Womit möchten Sie beginnen?",
		"home_btn_new": "Neu Beginnen",
		"home_btn_new_desc": "(CSV-Datei importieren)",
		"home_btn_load": "Sitzung laden",
		"home_btn_load_desc": "(.json-Datei laden)",
	"home_btn_info": "Info",

	// --- Info Page ---
	"info_modal_title":"🕊 Hey You🕊",
	"info_modal_message":" Please send me a nice Picture with Greets Thank You! %s",
	"modal_btn_close":"OK",

	 // --- Import Page ---
		"import_title": "CSV-Daten importieren",
		"import_desc": "Beginnen Sie, indem Sie einen Kontoauszug hochladen. Stellen Sie sicher, dass das Trennzeichen korrekt eingestellt ist.",
		"label_delimiter": "Trenner:",
		"label_currency": "Währung:",
		"btn_import_csv": "CSV Importieren",
		"load_json_title": "Sitzung laden",
		"load_json_desc": "Wählen Sie eine zuvor gespeicherte `.json`-Datei aus, um Ihre Daten und Regeln wiederherzustellen.",
		"load_settings_only" : "Nur Regeln laden",
		"btn_load_json": "JSON-Datei laden",
		
		// --- Mapping Step ---
		"mapping_title": "Felder zuweisen",
		"mapping_instruction_base": "Bitte ordnen Sie die folgenden Felder nacheinander durch anklicken der Tabellenüberschrift zu:",
		"mapping_btn_cancel": "Abbrechen",

		// --- Categorize Page ---
	"category_placeholder": "Unkategorisiert",
		"categorize_table_empty": "Keine Daten geladen.",
		"categorize_table_empty_sub": "Bitte importiere eine CSV Datei.",
		"rules_title": "Kategorisierungs-Regeln",
		"rules_search_label": "Verwendungszweck enthält:",
		"rules_search_placeholder": "z.B. REWE, Miete...",
		"rules_match_preview": "Treffer in 'Verwendungszweck'",
		"rules_category_label": "Setze Kategorie auf:",
		"rules_category_placeholder": "z.B. Lebensmittel",
		"rules_fixkosten_label": "Als Fixkosten markieren",
		"rules_btn_save": "Speichern & Anwenden",
		"rules_list_header": "Gespeicherte Regeln",
		"rules_btn_delete_all": "Alle löschen",
		"rules_btn_run_all": "Alle anwenden",
		"rules_list_empty": "Noch keine Regeln gespeichert.",
		"rules_btn_delete": "Regel löschen", // NEU
		
		// --- Visualize Page ---
		"vis_title": "Ausgaben-Analyse",
		"vis_label_from": "Von:",
		"vis_label_to": "Bis:",
	"vis_tab_pie":"Torte",
	"vis_tab_lines": "Linien",
	"vis_tab_stray": "Punkte",
		"vis_tab_details": "Details",
		"vis_chart_empty": "Keine Daten für diesen Zeitraum",
		"vis_chart_empty_sub": "Bitte Filter anpassen oder Daten kategorisieren.",
		"vis_chart_overview_empty": "Keine Daten für diesen Zeitraum",
		"vis_summary_income": "Einnahmen",
		"vis_summary_expenses": "Ausgaben",
		"vis_summary_balance": "Saldo",
	"vis_scatter_title":"Punktdiagramm",
	"vis_scatter_empty":"Leer",
	"vis_scatter_empty_sub":"Leer",
		"vis_nested_income": "Einnahmen",
		"vis_nested_variable": "Variable Ausgaben",
		"vis_nested_fixed": "Fixe Ausgaben",
		"vis_placeholder_no_income": "Keine Einnahmen in diesem Zeitraum",
		"vis_placeholder_no_variable": "Keine variablen Ausgaben in diesem Zeitraum",
		"vis_placeholder_no_fixed": "Keine fixen Ausgaben in diesem Zeitraum",
		"vis_chart_title": "Kategorisierte Ausgaben",
	"vis_nested_pie_overview":"Übersicht",
	"vis_nested_pie_expenses":"Kategorisert",
	"vis_lines_label": "Komma getrennte Kategorien:",
		"vis_lines_all": "Zusammenfassung",
		"vis_lines_top": "Top",
		"vis_chart_lines_empty": "Keine Daten für Liniendiagramm",
		"vis_chart_lines_empty_sub": "Bitte Zeitraum prüfen oder Kategorien eingeben.",
		"vis_chart_lines_empty_custom": "Keine Daten für gewählte Kategorien",
		"vis_chart_lines_empty_custom_sub": "Bitte Eingabe prüfen oder Zeitraum ändern.",
		"vis_lines_title": "Entwicklung im Zeitraum",
		"vis_lines_other": "Sonstige",

		// --- Table Column Headers  ---
		"Buchungstag": "Buchungstag", 
		"Verwendungszweck": "Verwendungszweck",
		"Betrag": "Betrag",
		"Kategorie": "Kategorie",
		"Fixkosten": "Fix",
	"Monat": "Month",

		// --- Dynamic Messages ---
		"msg_parsing_error": "Fehler beim CSV Import. Falsches Format? Bitte Trennzeichen prüfen.",
		"msg_crit_error": "Kritischer Fehler beim Lesen der Datei: ",
		"msg_all_fields_mapped": "Alle Felder zugewiesen. Verarbeite Daten...",
		"msg_import_canceled": "Import abgebrochen.",
		"msg_json_invalid": "Ungültiges JSON-Format. 'data' und 'rules' Arrays werden erwartet.",
		"msg_json_loaded": "%s Zeilen und %s Regeln erfolgreich geladen.",
		"msg_session_reset": "Sitzung zurückgesetzt.",
		"msg_no_data_to_save": "Keine Daten zum Speichern vorhanden.",
		"msg_json_saved": "Daten als JSON gespeichert.",
		"msg_csv_exported": "CSV mit %s Zeilen exportiert.",
		"msg_no_data_to_export": "Keine Daten zum Exportieren vorhanden.",
		"msg_rule_saved": "Regel gespeichert und %s Zeilen aktualisiert.",
		"msg_rule_exists": "Diese Regel existiert bereits.",
		"msg_rule_missing_fields": "Bitte Suchbegriff und Kategorie ausfüllen.",
		"msg_rules_applied": "Alle Regeln erneut angewendet. %s Aktualisierungen.",
		"msg_rules_applied_on_import": "Regeln auf Import angewendet. %s Aktualisierungen.",
		"msg_no_rules_to_delete": "Keine Regeln zum Löschen vorhanden.",
		"msg_rules_deleted": "Alle Regeln gelöscht und in der Tabelle entfernt.",
		"msg_rule_deleted_reapplied": "Regel gelöscht. Daten neu kategorisiert: %s Zeilen betroffen.",
		"confirm_reset_title": "Sitzung zurücksetzen?",
		"confirm_reset_message": "Möchten Sie wirklich alle importierten Daten und Regeln zurücksetzen? Sie werden zur Startseite weitergeleitet.",
		"confirm_reset_btn": "Zurücksetzen",
		"confirm_delete_all_rules_title": "Alle Regeln löschen?",
		"confirm_delete_all_rules_message": "Sind Sie sicher, dass Sie alle %s gespeicherten Kategorisierungs-Regeln löschen möchten? Dies kann nicht rückgängig gemacht werden. Die Kategorien und Fixkosten-Markierungen in der Tabelle werden ebenfalls entfernt.",
		"confirm_delete_all_rules_btn": "Ja, alle löschen",
		"confirm_delete_rule_title": "Regel löschen?",
		"confirm_delete_rule_message": "Möchten Sie die Regel \"%s -> %s\" wirklich löschen?",
		"confirm_delete_rule_btn": "Löschen",
	},
	"en": {
		// --- Navigation / Global ---
		"app_title": "Budget Book",
		"nav_home": "Home",
		"nav_import": "Import",
		"nav_categorize": "Categorization",
		"nav_visualize": "Visualization",
		"btn_reset": "Reset",
		"btn_save_json": "Save JSON",
		"btn_export_csv": "Export CSV",
		"status_placeholder": "Status messages here.",
		"modal_title_confirm": "Confirmation Required",
		"modal_message_default": "Are you sure you want to perform this action?",
		"modal_btn_cancel": "Cancel",
		"modal_btn_confirm": "Confirm",
		
		// --- Home Page ---
		"home_welcome_title": "Welcome!",
		"home_welcome_text": "What would you like to start with?",
		"home_btn_new": "Start New",
		"home_btn_new_desc": "(Import CSV file)",
		"home_btn_load": "Load Session",
		"home_btn_load_desc": "(Load .json file)",
	"home_btn_info": "Info",

	// --- Info Page ---
	"info_modal_title":"🕊 Hey You🕊",
	"info_modal_message":" Please send me a nice Picture with Greets Thank You! %s",
	"modal_btn_close":"OK",

	 // --- Import Page ---
		"import_title": "Import CSV Data",
		"import_desc": "Start by uploading a bank statement",
		"label_delimiter": "Delimiter:",
		"label_currency": "Currency:",
		"btn_import_csv": "Import CSV",
		"load_json_title": "Load Session",
		"load_json_desc": "Select a previously saved `.json` file to restore your data and rules.",
		"load_settings_only" : "Load only Rules",
		"btn_load_json": "Load JSON file",
		
		// --- Mapping Step ---
		"mapping_title": "Map Fields",
		"mapping_instruction_base": "Please map the following fields in order by clicking the table header:",
		"mapping_btn_cancel": "Cancel",

		// --- Categorize Page ---
	"category_placeholder": "Uncategorized",
		"categorize_table_empty": "No data loaded.",
		"categorize_table_empty_sub": "Please import a CSV file.",
		"rules_title": "Categorization Rules",
		"rules_search_label": "Purpose/Description contains:",
		"rules_search_placeholder": "e.g. Walmart, Rent...",
		"rules_match_preview": "Matches in 'Purpose/Description'",
		"rules_category_label": "Set category to:",
		"rules_category_placeholder": "e.g. Groceries",
		"rules_fixkosten_label": "Mark as fixed cost",
		"rules_btn_save": "Save & Apply",
		"rules_list_header": "Saved Rules",
		"rules_btn_delete_all": "Delete All",
		"rules_btn_run_all": "Apply All",
		"rules_list_empty": "No rules saved yet.",
		"rules_btn_delete": "Delete Rule",
		
		// --- Visualize Page ---
		"vis_title": "Expense Analysis",
		"vis_label_from": "From:",
		"vis_label_to": "To:",
	"vis_tab_pie":"Pie Chart",
	"vis_tab_lines": "Line Chart",
	"vis_tab_stray": "Points",
		"vis_tab_details": "Details",
		"vis_chart_empty": "No data for this period",
		"vis_chart_empty_sub": "Please adjust filters or categorize data.",
		"vis_chart_overview_empty": "No data for this period",
		"vis_summary_income": "Income",
		"vis_summary_expenses": "Expenses",
		"vis_summary_balance": "Balance",
	"vis_scatter_title":"Point diagram",
	"vis_scatter_empty":"Leer",
	"vis_scatter_empty_sub":"Leer",
		"vis_nested_income": "Income",
		"vis_nested_variable": "Variable Expenses",
		"vis_nested_fixed": "Fixed Expenses",
		"vis_placeholder_no_income": "No income in this period",
		"vis_placeholder_no_variable": "No variable expenses in this period",
		"vis_placeholder_no_fixed": "No fixed expenses in this period",
	"vis_nested_pie_overview":"Overview",
		"vis_chart_title": "Categorized Expenses (in period)",
	"vis_nested_pie_expenses":"Categorized",
		"vis_lines_all": "All",
		"vis_lines_top": "Top",
		"vis_lines_placeholder": "e.g. top",
		"vis_lines_other": "Other",
		"vis_chart_lines_empty": "No data for line chart",
		"vis_chart_lines_empty_sub": "Please check period or enter categories.",
		"vis_chart_lines_empty_custom": "No data for selected categories",
		"vis_chart_lines_empty_custom_sub": "Please check input or change period.",
		"vis_lines_title": "Lines over Time",

		// --- Table Column Headers  ---
		"Buchungstag": "Date", 
		"Verwendungszweck": "Purpose",
		"Betrag": "Amount",
		"Kategorie": "Category",
		"Fixkosten": "Fixed",
	"Monat": "Month",

		// --- Dynamic Messages ---
		"msg_parsing_error": "Error during CSV import. Wrong format? Please check delimiter.",
		"msg_crit_error": "Critical error reading file: ",
		"msg_all_fields_mapped": "All fields mapped. Processing data...",
		"msg_import_canceled": "Import canceled.",
		"msg_json_invalid": "Invalid JSON format. 'data' and 'rules' arrays are expected.",
		"msg_json_loaded": "%s rows and %s rules loaded successfully.",
		"msg_session_reset": "Session reset.",
		"msg_no_data_to_save": "No data to save.",
		"msg_json_saved": "Data saved as JSON.",
		"msg_csv_exported": "CSV exported with %s rows.",
		"msg_no_data_to_export": "No data to export.",
		"msg_rule_saved": "Rule saved and %s rows updated.",
		"msg_rule_exists": "This rule already exists.",
		"msg_rule_missing_fields": "Please fill in search term and category.",
		"msg_rules_applied": "All rules reapplied. %s updates.",
		"msg_rules_applied_on_import": "Rules applied on import. %s updates.",
		"msg_no_rules_to_delete": "No rules to delete.",
		"msg_rules_deleted": "All rules deleted and categories/fixed costs removed from table.",
		"msg_rule_deleted_reapplied": "Rule deleted. Data re-categorized: %s rows affected.",
		"confirm_reset_title": "Reset Session?",
		"confirm_reset_message": "Are you sure you want to reset all imported data and rules? You will be redirected to the home page.",
		"confirm_reset_btn": "Reset",
		"confirm_delete_all_rules_title": "Delete All Rules?",
		"confirm_delete_all_rules_message": "Are you sure you want to delete all %s saved categorization rules? This cannot be undone. The categories and fixed cost markers in the table will also be removed.",
		"confirm_delete_all_rules_btn": "Yes, delete all",
		"confirm_delete_rule_title": "Delete Rule?",
		"confirm_delete_rule_message": "Are you sure you want to delete the rule \"%s -> %s\"?",
		"confirm_delete_rule_btn": "Delete",
	},
	"fr": {
		// --- Navigation / Global ---
		"app_title": "Livre de comptes",
		"nav_home": "Accueil",
		"nav_import": "Importation",
		"nav_categorize": "Catégorisation",
		"nav_visualize": "Visualisation",
		"btn_reset": "Réinitialiser",
		"btn_save_json": "Sauvegarder JSON",
		"btn_export_csv": "Exporter CSV",
		"status_placeholder": "Messages de statut ici.",
		"modal_title_confirm": "Confirmation requise",
		"modal_message_default": "Êtes vous sûr de vouloir effectuer cette action ?",
		"modal_btn_cancel": "Annuler",
		"modal_btn_confirm": "Confirmer",
		
		// --- Home Page ---
		"home_welcome_title": "Bienvenue !",
		"home_welcome_text": "Par quoi souhaitez vous commencer ?",
		"home_btn_new": "Commencer",
		"home_btn_new_desc": "(Importer un fichier CSV)",
		"home_btn_load": "Charger la session",
		"home_btn_load_desc": "(Charger un fichier .json)",
	"home_btn_info": "Info",

	// --- Info Page ---
	"info_modal_title":"🕊 Hey You🕊",
	"info_modal_message":" Please send me a nice Picture with Greets Thank You! arjunae@nurFuerSpam.de",
	"modal_btn_close":"OK",

	 // --- Import Page ---
		"import_title": "Importer des données CSV",
		"import_desc": "Commencez par télécharger un relevé de compte. Assurez vous que le délimiteur est correctement défini.",
		"label_delimiter": "Délimiteur :",
		"label_currency": "Devise :",
		"btn_import_csv": "Importer CSV",
		"load_json_title": "Charger la session",
		"load_json_desc": "Sélectionnez un fichier `.json` précédemment enregistré pour restaurer vos données et règles.",
		"btn_load_json": "Charger le fichier JSON",
		
		// --- Mapping Step ---
		"mapping_title": "Assigner les champs",
		"mapping_instruction_base": "Veuillez assigner les champs suivants dans l'ordre en cliquant sur l'en-tête du tableau :",
		"mapping_btn_cancel": "Annuler",

		// --- Categorize Page ---
	"category_placeholder": "Non catégorisé",
		"categorize_table_empty": "Aucune donnée chargée.",
		"categorize_table_empty_sub": "Veuillez importer un fichier CSV.",
		"rules_title": "Règles de catégorisation",
		"rules_search_label": "Le libellé contient :",
		"rules_search_placeholder": "ex: Carrefour, Loyer...",
		"rules_match_preview": "Correspondances dans 'Libellé'",
		"rules_category_label": "Définir la catégorie à :",
		"rules_category_placeholder": "ex: Courses",
		"rules_fixkosten_label": "Marquer comme coût fixe",
		"rules_btn_save": "Sauvegarder & Appliquer",
		"rules_list_header": "Règles enregistrées",
		"rules_btn_delete_all": "Tout supprimer",
		"rules_btn_run_all": "Appliquer tout",
		"rules_list_empty": "Aucune règle enregistrée.",
		"rules_btn_delete": "Supprimer la règle",
		
		// --- Visualize Page ---
		"vis_title": "Analyse des dépenses",
		"vis_label_from": "Du :",
		"vis_label_to": "Au :",
	"vis_tab_pie":"Camembert",
	"vis_tab_lines": "Lignes",
	"vis_tab_stray": "Points",
		"vis_tab_details": "Détails",
		"vis_chart_empty": "Aucune donnée pour cette période",
		"vis_chart_empty_sub": "Veuillez ajuster les filtres ou catégoriser les données.",
		"vis_chart_overview_empty": "Aucune donnée pour cette période",
		"vis_summary_income": "Revenus",
		"vis_summary_expenses": "Dépenses",
		"vis_summary_balance": "Solde",
		"vis_nested_income": "Revenus",
		"vis_nested_variable": "Dépenses variables",
		"vis_nested_fixed": "Dépenses fixes",
		"vis_placeholder_no_income": "Aucun revenu durant cette période",
		"vis_placeholder_no_variable": "Aucune dépense variable durant cette période",
		"vis_placeholder_no_fixed": "Aucune dépense fixe durant cette période",
		"vis_chart_title": "Dépenses catégorisées (sur la période)",
	"vis_nested_pie_overview":"Overview",
	"vis_nested_pie_expenses":"Catégorisé",
	"vis_lines_label": "Catégories séparées par des virgules :",
		"vis_lines_placeholder": "ex: top4",
		"vis_chart_lines_empty": "Aucune donnée pour le graphique linéaire",
		"vis_chart_lines_empty_sub": "Veuillez vérifier la période ou saisir des catégories.",
		"vis_chart_lines_empty_custom": "Aucune donnée pour les catégories sélectionnées",
		"vis_chart_lines_empty_custom_sub": "Veuillez vérifier la saisie ou changer la période.",
		"vis_lines_title": "Lignes dans le temps",

		// --- Table Column Headers  ---
		"Buchungstag": "Date", 
		"Verwendungszweck": "Libellé",
		"Betrag": "Montant",
		"Kategorie": "Catégorie",
		"Fixkosten": "Fixe",
	"Monat": "Mois",

		// --- Dynamic Messages ---
		"msg_parsing_error": "Erreur lors de l'importation CSV. Mauvais format ? Veuillez vérifier le délimiteur.",
		"msg_crit_error": "Erreur critique lors de la lecture du fichier : ",
		"msg_all_fields_mapped": "Tous les champs sont assignés. Traitement des données...",
		"msg_import_canceled": "Importation annulée.",
		"msg_json_invalid": "Format JSON invalide. Les tableaux 'data' et 'rules' sont attendus.",
		"msg_json_loaded": "%s lignes et %s règles chargées avec succès.",
		"msg_session_reset": "Session réinitialisée.",
		"msg_no_data_to_save": "Aucune donnée à sauvegarder.",
		"msg_json_saved": "Données sauvegardées en JSON.",
		"msg_csv_exported": "CSV exporté avec %s lignes.",
		"msg_no_data_to_export": "Aucune donnée à exporter.",
		"msg_rule_saved": "Règle enregistrée et %s lignes mises à jour.",
		"msg_rule_exists": "Cette règle existe déjà.",
		"msg_rule_missing_fields": "Veuillez remplir le terme de recherche et la catégorie.",
		"msg_rules_applied": "Toutes les règles réappliquées. %s mises à jour.",
		"msg_rules_applied_on_import": "Règles appliquées à l'importation. %s mises à jour.",
		"msg_no_rules_to_delete": "Aucune règle à supprimer.",
		"msg_rules_deleted": "Toutes les règles supprimées et catégories/coûts fixes retirés du tableau.",
		"msg_rule_deleted_reapplied": "Règle supprimée. Données re-catégorisées : %s lignes affectées.",
		"confirm_reset_title": "Réinitialiser la session ?",
		"confirm_reset_message": "Êtes-vous sûr de vouloir réinitialiser toutes les données et règles importées ? Vous serez redirigé vers la page d'accueil.",
		"confirm_reset_btn": "Réinitialiser",
		"confirm_delete_all_rules_title": "Supprimer toutes les règles ?",
		"confirm_delete_all_rules_message": "Êtes-vous sûr de vouloir supprimer les %s règles de catégorisation enregistrées ? Cela ne peut pas être annulé. Les catégories et les marqueurs de coûts fixes dans le tableau seront également supprimés.",
		"confirm_delete_all_rules_btn": "Oui, tout supprimer",
		"confirm_delete_rule_title": "Supprimer la règle ?",
		"confirm_delete_rule_message": "Êtes-vous sûr de vouloir supprimer la règle \"%s -> %s\" ?",
		"confirm_delete_rule_btn": "Supprimer",
	},
	"es": {
		// --- Navigation / Global ---
		"app_title": "Libro de cuentas",
		"nav_home": "Inicio",
		"nav_import": "Importar",
		"nav_categorize": "Categorización",
		"nav_visualize": "Visualización",
		"btn_reset": "Reiniciar",
		"btn_save_json": "Guardar JSON",
		"btn_export_csv": "Exportar CSV",
		"status_placeholder": "Mensajes de estado aquí.",
		"modal_title_confirm": "Confirmación requerida",
		"modal_message_default": "¿Está seguro de que desea realizar esta acción?",
		"modal_btn_cancel": "Cancelar",
		"modal_btn_confirm": "Confirmar",
		
		// --- Home Page ---
		"home_welcome_title": "¡Bienvenido!",
		"home_welcome_text": "¿Con qué le gustaría empezar?",
		"home_btn_new": "Empezar de nuevo",
		"home_btn_new_desc": "(Importar archivo CSV)",
		"home_btn_load": "Cargar sesión",
		"home_btn_load_desc": "(Cargar archivo .json)",
	"home_btn_info": "Info",

	// --- Info Page ---
	"info_modal_title":"🕊 Hey You🕊",
	"info_modal_message":" Please send me a nice Picture with Greets Thank You! arjunae@nurFuerSpam.de",
	"modal_btn_close":"OK",

	 // --- Import Page ---
		"import_title": "Importar datos CSV",
		"import_desc": "Comience cargando un extracto bancario. Asegúrese de que el delimitador esté configurado correctamente.",
		"label_delimiter": "Delimitador:",
		"label_currency": "Moneda:",
		"btn_import_csv": "Importar CSV",
		"load_json_title": "Cargar sesión",
		"load_json_desc": "Seleccione un archivo `.json` guardado previamente para restaurar sus datos y reglas.",
		"btn_load_json": "Cargar archivo JSON",
		
		// --- Mapping Step ---
		"mapping_title": "Asignar campos",
		"mapping_instruction_base": "Asigne los siguientes campos en orden haciendo clic en el encabezado de la tabla:",
		"mapping_btn_cancel": "Cancelar",

		// --- Categorize Page ---
	"category_placeholder": "Sin categorizar",
		"categorize_table_empty": "No hay datos cargados.",
		"categorize_table_empty_sub": "Por favor, importe un archivo CSV.",
		"rules_title": "Reglas de categorización",
		"rules_search_label": "El concepto contiene:",
		"rules_search_placeholder": "ej: Mercadona, Alquiler...",
		"rules_match_preview": "Coincidencias en 'Concepto'",
		"rules_category_label": "Establecer categoría a:",
		"rules_category_placeholder": "ej: Supermercado",
		"rules_fixkosten_label": "Marcar como costo fijo",
		"rules_btn_save": "Guardar y aplicar",
		"rules_list_header": "Reglas guardadas",
		"rules_btn_delete_all": "Eliminar todo",
		"rules_btn_run_all": "Aplicar todo",
		"rules_list_empty": "Aún no hay reglas guardadas.",
		"rules_btn_delete": "Eliminar regla",
		
		// --- Visualize Page ---
		"vis_title": "Análisis de gastos",
		"vis_label_from": "Desde:",
		"vis_label_to": "Hasta:",
	"vis_tab_pie":"Gráfico circular",
	"vis_tab_lines": "Líneas",
	"vis_tab_stray": "Points",
		"vis_tab_details": "Detalles",
		"vis_chart_empty": "No hay datos para este período",
		"vis_chart_empty_sub": "Ajuste los filtros o categorice los datos.",
		"vis_chart_overview_empty": "No hay datos para este período",
		"vis_summary_income": "Ingresos",
		"vis_summary_expenses": "Gastos",
		"vis_summary_balance": "Saldo",
		"vis_nested_income": "Ingresos",
		"vis_nested_variable": "Gastos variables",
		"vis_nested_fixed": "Gastos fijos",
		"vis_placeholder_no_income": "No hay ingresos en este período",
		"vis_placeholder_no_variable": "No hay gastos variables en este período",
		"vis_placeholder_no_fixed": "No hay gastos fijos en este período",
		"vis_chart_title": "Gastos categorizados (en el período)",
	"vis_nested_pie_overview":"Overview",
	"vis_nested_pie_expenses":"Categorizado",
	"vis_lines_label": "Categorías separadas por comas:",
		"vis_lines_placeholder": "ej: top4",
		"vis_chart_lines_empty": "No hay datos para el gráfico de líneas",
		"vis_chart_lines_empty_sub": "Compruebe el período o ingrese categorías.",
		"vis_chart_lines_empty_custom": "No hay datos para las categorías seleccionadas",
		"vis_chart_lines_empty_custom_sub": "Compruebe la entrada o cambie el período.",
		"vis_lines_title": "Líneas a lo largo del tiempo",

		// --- Table Column Headers  ---
		"Buchungstag": "Fecha", 
		"Verwendungszweck": "Concepto",
		"Betrag": "Importe",
		"Kategorie": "Categoría",
		"Fixkosten": "Fijo",
	"Monat": "Mes",

		// --- Dynamic Messages ---
		"msg_parsing_error": "Error al importar CSV. ¿Formato incorrecto? Por favor, revise el delimitador.",
		"msg_crit_error": "Error crítico al leer el archivo: ",
		"msg_all_fields_mapped": "Todos los campos asignados. Procesando datos...",
		"msg_import_canceled": "Importación cancelada.",
		"msg_json_invalid": "Formato JSON no válido. Se esperan los arrays 'data' y 'rules'.",
		"msg_json_loaded": "%s filas y %s reglas cargadas con éxito.",
		"msg_session_reset": "Sesión reiniciada.",
		"msg_no_data_to_save": "No hay datos para guardar.",
		"msg_json_saved": "Datos guardados como JSON.",
		"msg_csv_exported": "CSV exportado con %s filas.",
		"msg_no_data_to_export": "No hay datos para exportar.",
		"msg_rule_saved": "Regla guardada y %s filas actualizadas.",
		"msg_rule_exists": "Esta regla ya existe.",
		"msg_rule_missing_fields": "Por favor, rellene el término de búsqueda y la categoría.",
		"msg_rules_applied": "Todas las reglas reaplicadas. %s actualizaciones.",
		"msg_rules_applied_on_import": "Reglas aplicadas en la importación. %s actualizaciones.",
		"msg_no_rules_to_delete": "No hay reglas para eliminar.",
		"msg_rules_deleted": "Todas las reglas eliminadas y categorías/costos fijos eliminados de la tabla.",
		"msg_rule_deleted_reapplied": "Regla eliminada. Datos re-categorizados: %s filas afectadas.",
		"confirm_reset_title": "¿Reiniciar sesión?",
		"confirm_reset_message": "¿Está seguro de que desea reiniciar todos los datos y reglas importados? Será redirigido a la página de inicio.",
		"confirm_reset_btn": "Reiniciar",
		"confirm_delete_all_rules_title": "¿Eliminar todas las reglas?",
		"confirm_delete_all_rules_message": "¿Está seguro de que desea eliminar todas las %s reglas de categorización guardadas? Esto no se puede deshacer. Las categorías y los marcadores de costos fijos en la tabla también se eliminarán.",
		"confirm_delete_all_rules_btn": "Sí, eliminar todo",
		"confirm_delete_rule_title": "¿Eliminar regla?",
		"confirm_delete_rule_message": "¿Está seguro de que desea eliminar la regla \"%s -> %s\"?",
		"confirm_delete_rule_btn": "Eliminar",
	}
};

// Helper function for localization lookup (L for Lookup or Locale)
window.L = function(key, ...args) {
	const locale = locales[currentLocaleKey] || locales['de'];
	let text = locale[key] || locales['de'][key] || `[MISSING: ${key}]`;
	
	// Simple placeholder replacement for dynamic messages
	args.forEach(arg => {
		text = text.replace('%s', arg); 
	});
	return text;
}

window.locales = locales;
